name: Boolean Tests

on:
  schedule:
    - cron: "0 16 * * *" # Runs at 4 PM every day
  workflow_dispatch: # Allows manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install

      - name: Run Boolean Tests
        id: test
        run: yarn test:boolean
        continue-on-error: true

      - name: Send Webhook Notification
        if: always()
        run: |
          if [ "${{ steps.test.outcome }}" == "success" ]; then
            curl -s -X POST \
              -H "Content-Type: application/json" \
              -d '{
                "target": "grp_2yWp96RAONNHFQYzt90WPX7kQ6t",
                "text": "Boolean tests completed successfully!"
              }' \
              "https://api.gluegroups.com/webhook/wbh_2yZh5T3LGghnqssM9FiLmuvOaL1/hwOrFjdYaWOrGjCFnRDbMRmCB4SRozGOsOruu89i8UE"
          else
            curl -s -X POST \
              -H "Content-Type: application/json" \
              -d '{
                "target": "grp_2yWp96RAONNHFQYzt90WPX7kQ6t",
                "text": "Boolean tests failed!"
              }' \
              "https://api.gluegroups.com/webhook/wbh_2yZh5T3LGghnqssM9FiLmuvOaL1/hwOrFjdYaWOrGjCFnRDbMRmCB4SRozGOsOruu89i8UE"
          fi
