name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  setup-vpn:
    uses: ./.github/workflows/vpn.yml

  test:
    needs: setup-vpn
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - run: echo "Tests sẽ chạy ở đây"
