name: Simple Tests

on:
  schedule:
    - cron: "0 15 * * *" # Runs at 3 PM every day
  workflow_dispatch: # Allows manual trigger

jobs:
  setup-vpn:
    uses: ./.github/workflows/vpn.yml
  test:
    needs: setup-vpn
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install

      - name: Run Simple Tests
        id: test
        run: |
          echo "Starting simple tests..."
          yarn test:simple
          echo "Test execution completed with status: $?"
        continue-on-error: true
