name: "Simple Tests"

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install

      - name: Run Simple Tests
        id: test
        run: |
          echo "Starting simple tests..."
          yarn test:simple
          echo "Test execution completed with status: $?"
        continue-on-error: true

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-html-report
          path: playwright-report/index.html
          retention-days: 30

      - name: Get Artifact ID
        id: get_artifact
        run: |
          ARTIFACT_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts | \
            jq -r '.artifacts[] | select(.name=="playwright-html-report") | .id')

          echo "artifact_id=$ARTIFACT_ID" >> $GITHUB_OUTPUT

      - name: Send Result Link to GlueGroups Webhook
        if: ${{ !cancelled() }}
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          TARGET_ID: ${{ secrets.TARGET_GROUP_GLUE_ID }}
        run: |
          ARTIFACT_ID="${{ steps.get_artifact.outputs.artifact_id }}"
          RUN_ID="${{ github.run_id }}"
          REPO_URL="https://github.com/${{ github.repository }}"
          ARTIFACT_LINK="$REPO_URL/actions/runs/$RUN_ID/artifacts/$ARTIFACT_ID"

          curl -X POST "$WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d "$(jq -n \
              --arg target "$TARGET_ID" \
              --arg text "✅ Simple Tests Success. 📎 [View full report]($ARTIFACT_LINK)" \
              '{target: $target, text: $text}')"
