---
name: "Simple Tests"
"on":
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch: null
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Setup Node.js"
        uses: "actions/setup-node@v4"
        with:
          node-version: "20"
      - name: "Install dependencies"
        run: "yarn install"
      - name: "Run Simple Tests"
        id: "test"
        run: "echo \"Starting simple tests...\"\nyarn test:simple\necho \"Test execution completed with status: $?\"\n"
        continue-on-error: true
      - name: "Upload Playwright Report"
        uses: "actions/upload-artifact@v4"
        if: "${{ !cancelled() }}"
        with:
          name: "playwright-html-report"
          path: "playwright-report/index.html"
          retention-days: 30
      - name: "Get Artifact ID"
        id: "get_artifact"
        run: "ARTIFACT_ID=$(curl -s -H \"Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}\" \\\n  https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts | \\\n  jq -r '.artifacts[] | select(.name==\"playwright-html-report\") | .id')\n\necho \"artifact_id=$ARTIFACT_ID\" >> $GITHUB_OUTPUT\n"
      - name: "Send Result Link to GlueGroups Webhook"
        if: "${{ !cancelled() }}"
        env:
          WEBHOOK_URL: "https://api.gluegroups.com/webhook/wbh_2yZh5T3LGghnqssM9FiLmuvOaL1/hwOrFjdYaWOrGjCFnRDbMRmCB4SRozGOsOruu89i8UE"
          TARGET_ID: "grp_2yWp96RAONNHFQYzt90WPX7kQ6t"
        run: "ARTIFACT_ID=\"${{ steps.get_artifact.outputs.artifact_id }}\"\nRUN_ID=\"${{ github.run_id }}\"\nREPO_URL=\"https://github.com/${{ github.repository }}\"\nARTIFACT_LINK=\"$REPO_URL/actions/runs/$RUN_ID/artifacts/$ARTIFACT_ID\"\n\ncurl -X POST \"$WEBHOOK_URL\" \\\n  -H \"Content-Type: application/json\" \\\n  -d \"$(jq -n \\\n    --arg target \"$TARGET_ID\" \\\n    --arg text \"✅ Simple Tests Success. View full report: $ARTIFACT_LINK\" \\\n    '{target: $target, text: $text}')\"\n"
