name: Setup VPN via Tailscale

on:
  workflow_call:

jobs:
  vpn:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: "tskey-auth-kjJkXWLH1B21CNTRL-r4iefXc2XSZnW7yaLhaLSZMhT9zVEGp2"
          hostname: github-runner-vpn
