name: Setup VPN via Tailscale

on:
  workflow_call:

jobs:
  vpn:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: "kPwKiUhns921CNTRL"
          oauth-secret: "tskey-client-kPwKiUhns921CNTRL-rsXVs8eZDLVpeDXT7bmJMV8ALBRDjZTh"
          tags: tag:github-action
          version: latest
