name: Setup VPN via Tailscale

on:
  workflow_call:

jobs:
  vpn:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: "tskey-auth-kj4RTHCXf221CNTRL-K2FMfXrZhbRMTwSJdrvfbRFJHnTSb4PL"
          hostname: github-runner-vpn
