name: Setup VPN via Tailscale

on:
  workflow_call:

jobs:
  vpn:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: "kGFr1A2HPx11CNTRL"
          oauth-secret: "tskey-client-kGFr1A2HPx11CNTRL-YjuNm74kwP8gMoKP8cLPP8NLmts4r14TL"
          tags: tag:github-action
          version: latest
