name: Setup VPN via Tailscale

on:
  workflow_call:

jobs:
  vpn:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: "kL1hg3Bvp911CNTRL"
          oauth-secret: "tskey-client-kL1hg3Bvp911CNTRL-7G2mgvnpqzC3nPfWhgD4zCveSGWJ1qjoR"
          tags: tag:github-action
          version: latest
