name: Setup VPN via Tailscale

on:
  workflow_call:

jobs:
  vpn:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Tailscale VPN
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          hostname: github-runner-vpn
