name: Setup VPN via Tailscale

on:
  workflow_call:

jobs:
  vpn:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Tailscale VPN
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          hostname: github-runner-vpn
