# .github/workflows/vpn.yml
name: Setup VPN

on:
  workflow_call:
    secrets:
      TAILSCALE_AUTHKEY:
        required: true

jobs:
  tailscale:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
